[platformio]
default_envs = stm32f401cc_usb
src_dir = firmware
include_dir = firmware/Core/Inc

[env:stm32f401cc_usb]
platform = ststm32
board = genericSTM32F401CC
upload_protocol = stlink
debug_tool = stlink
extra_scripts =
    pre:tools/platformio_pre.py
    post:tools/platformio_post.py
build_src_filter =
    +<Core/Src/*.c>
    +<startup/*.s>
    -<Core/Src/platform_usb_cdc_template.c>
build_flags =
    -DSTM32F401xC
    -DUSE_USB_FS
    -ffreestanding
    -Wall
    -Wextra
    -Werror
    -I$PROJECT_DIR/firmware/Core/Inc
build_unflags =
    -Os
monitor_speed = 115200
